parameters:
  database_driver: pdo_sqlite
  database_path: /tmp/fancontrol.db
  database_paths: [%kernel.root_dir%/../Entity]

services:
  loop:
    class: React\EventLoop\LoopInterface
    factory_class: \React\EventLoop\Factory
    factory_method: create

  event_dispatcher:
    class: Symfony\Component\EventDispatcher\EventDispatcher
    calls:
      - [addSubscriber, [@kernel.router_listener]]
      - [addSubscriber, [@kernel.exception_listener]]

  controller_resolver:
    class: Fieg\Fancontrol\Controller\ControllerResolver
    arguments: [@service_container]

  http.kernel:
    class: Symfony\Component\HttpKernel\HttpKernel
    arguments: [@event_dispatcher, @controller_resolver]

  file_locator:
    class: Symfony\Component\Config\FileLocator
    arguments:
      - [%kernel.root_dir%]

  routes:
    class: Symfony\Component\Routing\RouteCollection

  request_context:
    class: Symfony\Component\Routing\RequestContext

  annotation_reader:
    class: Doctrine\Common\Annotations\AnnotationReader

  AnnotatedRouteControllerLoader:
    class: Fieg\Fancontrol\Routing\AnnotatedRouteControllerLoader
    arguments: [@annotation_reader]

  AnnotationDirectoryLoader:
    class: Symfony\Component\Routing\Loader\AnnotationDirectoryLoader
    arguments: [@file_locator, @AnnotatedRouteControllerLoader, [%kernel.root_dir%/../Controller]]

  route_collection:
    class: Symfony\Component\Routing\RouteCollection

  url_matcher:
    class: Symfony\Component\Routing\Matcher\UrlMatcher
    arguments: [@route_collection, @request_context]

  kernel.router_listener:
    class: Symfony\Component\HttpKernel\EventListener\RouterListener
    arguments: [@url_matcher]

  kernel.exception_listener:
    class: Symfony\Component\HttpKernel\EventListener\ExceptionListener
    arguments: ["Fieg\Fancontrol\Controller\ExceptionController::errorAction"]

  doctrine.config:
    class: Doctrine\ORM\Configuration
    factory_class: Doctrine\ORM\Tools\Setup
    factory_method: createAnnotationMetadataConfiguration
    arguments: [%database_paths%, true, ~, ~, false]

  doctrine.entity_manager:
    class: Doctrine\ORM\EntityManager
    factory_class: Doctrine\ORM\EntityManager
    factory_method: create
    arguments:
      -
        driver: %database_driver%
        path: %database_path%
      - @doctrine.config

  twig.loader:
    class: Twig_Loader_Filesystem
    arguments: [%kernel.root_dir%/../Resources]

  twig:
    class: Twig_Environment
    arguments: [@twig.loader]
